@startuml
'https://plantuml.com/sequence-diagram
class HeroAircraft {
    - shootNum:int
    - power:int
    - direction:int
    + strategy:Strategy
    - HeroAircraft(int locationX, int locationY, int speedX, int speedY, int hp)
    - {static}hero:HeroAircraft
    + {static}GetHeroAircraft():HeroAircraft
    + forward():void
    + shoot():List<BaseBullet>
    + add_blood():void
}
HeroAircraft <--HeroAircraft
@enduml